name: Build
on:
    push:
        branches: [master]
jobs:
    #Job neve tetszőlegesen választható
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                cache: 'pip'
            - name: Install dependecies
              run: pip install -c contraints.txt .[dev]
            - name: static analysis
              run: pre-commit run --all-files
            - name: Unit test
              run: pytest - v test/unit
            - name: Create docker image
              run: docker build -t employees-python .
